name: training_timer
description: "Fitness app for custom workout timers with intervals, rest periods, and exercise sequences."
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_secure_storage: ^9.2.2
  dio: ^5.7.0
  go_router: ^14.3.0
  flutter_riverpod: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mocktail: ^0.3.0

flutter:
  assets:
    - .env
